# Books Recommendation system using clustering | Collaborative based

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
books=pd.read_csv("Books.csv")

C:\Users\alubi\AppData\Local\Temp\ipykernel_18684\1463327289.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books=pd.read_csv("Books.csv")

In [4]:
books.shape

(271360, 8)

In [5]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [6]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [7]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [8]:
books.drop(columns=['Image-URL-S', 'Image-URL-M'],inplace=True)

In [9]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-L'],
      dtype='object')

In [10]:
books.rename(columns={
    "Book-Title":"title",
    "Book-Author":"Author",
    "Year-of-Publication":"yop",
    "Image-URL-L":"img",
    "Publisher":"publisher"
},inplace=True)

In [11]:
users=pd.read_csv("Users.csv")

In [12]:
users.shape

(278858, 3)

In [13]:
ratings=pd.read_csv("Ratings.csv")

In [14]:
print(books.shape)
print(users.shape)
print(ratings.shape)

(271360, 6)
(278858, 3)
(1149780, 3)

In [15]:
ratings.head(2)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5

In [16]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [17]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [18]:
 users.rename(columns={
    "User-ID":"user_id",
    "Location":"location",
    "Age":"age",
},inplace=True)

In [19]:
 ratings.rename(columns={
    "User-ID":"user_id",
    "Book-Rating":"rating",
},inplace=True)

In [20]:
users.columns

Index(['user_id', 'location', 'age'], dtype='object')

In [21]:
ratings['user_id'].value_counts()

user_id
11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
          ...
116180        1
116166        1
116154        1
116137        1
276723        1
Name: count, Length: 105283, dtype: int64

In [22]:
ratings['user_id'].shape

(1149780,)

In [23]:
x=ratings['user_id'].value_counts() > 60

In [24]:
len(x)

105283

In [25]:
ratings=ratings[ratings['user_id'].isin(x[x].index)]

In [26]:
ratings.head()

     user_id        ISBN  rating
412   276925  0006511929       0
413   276925  002542730X      10
414   276925  0060520507       0
415   276925  0060930934       0
416   276925  0060951303       0

In [27]:
ratings['user_id'].value_counts()

user_id
11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
          ...
172374       61
242499       61
101214       61
3373         61
126395       61
Name: count, Length: 2884, dtype: int64

In [28]:
# dummy=books.merge(ratings,on="ISBN")

In [29]:
# dummy.shape

In [30]:
ratings_with_books=ratings.merge(books,on="ISBN")

In [31]:
ratings_with_books['user_id'].value_counts()

user_id
11676     11144
198711     6456
153662     5814
98391      5779
35859      5646
          ...
23725         7
66619         5
172941        5
100345        3
224108        1
Name: count, Length: 2884, dtype: int64

In [32]:
ratings_with_books.shape

(677214, 8)

In [33]:
ratings_with_books.rename(columns={
    "Year-Of-Publication":"yop",
},inplace=True)

In [34]:
print(books.groupby("title"))

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001D7802CA310>

In [35]:
temp=ratings_with_books.groupby('title')['rating'].count().reset_index()

In [36]:
temp

                                                    title  rating
0        A Light in the Storm: The Civil War Diary of ...       4
1                                   Always Have Popsicles       1
2                    Apple Magic (The Collector's series)       1
3        Ask Lily (Young Women of Faith: Lily Series, ...       1
4        Beyond IBM: Leadership Marketing and Finance ...       1
...                                                   ...     ...
195005                   Ã?Â?berraschung am Valentinstag.       1
195006                                      Ã?Â?lpiraten.       1
195007                     Ã?Â?rger mit Produkt X. Roman.       3
195008                              Ã?Â?stlich der Berge.       1
195009                                  Ã?Â?thique en toc       2

[195010 rows x 2 columns]

In [37]:
temp.rename(columns={
    "rating":"num_rating",
},inplace=True)

In [38]:
temp.head()

                                               title  num_rating
0   A Light in the Storm: The Civil War Diary of ...           4
1                              Always Have Popsicles           1
2               Apple Magic (The Collector's series)           1
3   Ask Lily (Young Women of Faith: Lily Series, ...           1
4   Beyond IBM: Leadership Marketing and Finance ...           1

In [39]:
ratings_with_books=ratings_with_books.merge(temp,on="title")

In [40]:
ratings_with_books.shape

(677214, 9)

In [41]:
final_rating=ratings_with_books[ratings_with_books['num_rating']>= 50]

In [42]:
final_rating

,user_id,ISBN,rating,title,Author,yop,publisher,img,num_rating
0,276925,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,119
5,276925,0140327592,0,Matilda,Roald Dahl,1990,Viking Penguin Inc,http://images.amazon.com/images/P/0140327592.0...,86
12,276925,0316666343,0,The Lovely Bones: A Novel,Alice Sebold,2002,"Little, Brown",http://images.amazon.com/images/P/0316666343.0...,533
15,276925,0385504209,8,The Da Vinci Code,Dan Brown,2003,Doubleday,http://images.amazon.com/images/P/0385504209.0...,414
37,276925,0804106304,0,The Joy Luck Club,Amy Tan,1994,Prentice Hall (K-12),http://images.amazon.com/images/P/0804106304.0...,307
...,...,...,...,...,...,...,...,...,...
677180,276688,0553575104,6,In Pursuit of the Proper Sinner,Elizabeth George,2000,Bantam Books,http://images.amazon.com/images/P/0553575104.0...,62
677187,276688,0679419810,0,Strip Tease,Carl Hiaasen,1993,Random House Inc,http://images.amazon.com/images/P/0679419810.0...,62
677191,276688,0679751521,0,Midnight in the Garden of Good and Evil,John Berendt,1999,Vintage Books USA,http://images.amazon.com/images/P/0679751521.0...,99
677196,276688,068484267X,0,Angela's Ashes: A Memoir,Frank McCourt,1999,Scribner,http://images.amazon.com/images/P/068484267X.0...,126
677207,276688,0788192043,0,The Hundred Secret Senses,Amy Tan,2000,DIANE Publishing Company,http://images.amazon.com/images/P/0788192043.0...,195

In [43]:
final_rating['user_id'].value_counts()

user_id
11676     1484
35859      679
76352      607
16795      554
153662     547
          ...
47534        1
242465       1
257368       1
148966       1
261379       1
Name: count, Length: 2772, dtype: int64

In [44]:
final_rating.shape

(126264, 9)

In [45]:
final_rating.drop_duplicates(['title','user_id'],inplace=True)

C:\Users\alubi\AppData\Local\Temp\ipykernel_18684\3106067650.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_rating.drop_duplicates(['title','user_id'],inplace=True)

In [46]:
final_rating.isnull().sum()

user_id       0
ISBN          0
rating        0
title         0
Author        0
yop           0
publisher     0
img           0
num_rating    0
dtype: int64

In [47]:
x=final_rating['user_id'].value_counts() > 60

In [48]:
dummy_final=final_rating[final_rating['user_id'].isin(x[x].index)]

In [66]:
dummy_book_pivot=dummy_final.pivot_table(columns='user_id',index='title',values='rating')

In [67]:
dummy_book_pivot.head(20)

user_id,254,3363,4017,5903,6251,6543,6563,6575,7158,7346,...,273086,273113,273979,274004,274061,274301,274308,275970,277427,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010: Odyssey Two,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204 Rosewood Lane,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24 Hours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,10.0,NaN
2nd Chance,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
4 Blondes,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84 Charing Cross Road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN
A 2nd Helping of Chicken Soup for the Soul (Chicken Soup for the Soul Series (Paper)),NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Beautiful Mind: The Life of Mathematical Genius and Nobel Laureate John Nash,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Bend in the Road,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,5.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Case of Need,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,7.0,NaN,NaN,0.0
"A Child Called \It\"": One Child's Courage to Survive""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Civil Action,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Confederacy of Dunces (Evergreen Book),NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Cry In The Night,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
A Dangerous Fortune,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Darkness More Than Night,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Day Late and a Dollar Short,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Density of Souls,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
dummy_book_pivot.fillna(0,inplace=True)

In [52]:
dummy_book_pivot.index[0]

'1984'

In [53]:
from scipy.sparse import csr_matrix

In [54]:
book_sparse=csr_matrix(dummy_book_pivot)

In [55]:
from sklearn.neighbors import NearestNeighbors
model=NearestNeighbors(algorithm='brute')

In [56]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [57]:
distances, suggestion = model.kneighbors(dummy_book_pivot.iloc[6,:].values.reshape(1,-1),n_neighbors=6)

In [58]:
suggestion

array([[   6, 1224,  749,  442, 1034,  471]], dtype=int64)

In [59]:
for i in range(len(suggestion)):
    print(dummy_book_pivot.index[suggestion[i]])

Index(['4 Blondes',
       'Tom Clancy's Op-Center: Games of State (Tom Clancy's Op Center (Paperback))',
       'Ruthless.Com (Tom Clancy's Power Plays (Paperback))', 'High Tide',
       'The Icarus Agenda', 'In Pursuit of the Proper Sinner'],
      dtype='object', name='title')

In [60]:
books_name=dummy_book_pivot.index

In [61]:
books_name

Index(['1984', '1st to Die: A Novel', '2010: Odyssey Two', '204 Rosewood Lane',
       '24 Hours', '2nd Chance', '4 Blondes', '84 Charing Cross Road',
       'A 2nd Helping of Chicken Soup for the Soul (Chicken Soup for the Soul Series (Paper))',
       'A Beautiful Mind: The Life of Mathematical Genius and Nobel Laureate John Nash',
       ...
       'Wizard and Glass (The Dark Tower, Book 4)',
       'Women Who Run with the Wolves',
       'Word Freak: Heartbreak, Triumph, Genius, and Obsession in the World of Competitive Scrabble Players',
       'Wuthering Heights', 'Wuthering Heights (Penguin Classics)',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='title', length=1313)

In [62]:
def recommend_books(book_name):
    book_index=np.where(dummy_book_pivot.index==book_name)[0][0]
    distances, suggestion = model.kneighbors(dummy_book_pivot.iloc[6,:].values.reshape(1,-1),n_neighbors=6)
    for i in range(len(suggestion)):
        books=(dummy_book_pivot.index[suggestion[i]])
        for j in books:
            print(j)

In [63]:
recommend_books('24 Hours')

4 Blondes
Tom Clancy's Op-Center: Games of State (Tom Clancy's Op Center (Paperback))
Ruthless.Com (Tom Clancy's Power Plays (Paperback))
High Tide
The Icarus Agenda
In Pursuit of the Proper Sinner